/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedAlbumIdRouteImport } from './routes/_authenticated/album.$id'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlbumIdRoute = AuthenticatedAlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/search': typeof AuthenticatedSearchRoute
  '/album/$id': typeof AuthenticatedAlbumIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/search': typeof AuthenticatedSearchRoute
  '/album/$id': typeof AuthenticatedAlbumIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/album/$id': typeof AuthenticatedAlbumIdRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/discover' | '/search' | '/album/$id' | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/discover' | '/search' | '/album/$id' | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/discover'
    | '/_authenticated/search'
    | '/_authenticated/album/$id'
    | '/_authenticated/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/album/$id': {
      id: '/_authenticated/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AuthenticatedAlbumIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedAlbumIdRoute: typeof AuthenticatedAlbumIdRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedAlbumIdRoute: AuthenticatedAlbumIdRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
